import { Fact } from '@/types/api'

export const factsDB: Fact[] = [
  {
    id: 0,
    content: 'Toyota Camry',
    points: 0,
    costs: 'medium',
    status: 'sport',
    type: 'sedan',
    speed: 'fast',
    refuel: 'fuel',
  },
  {
    id: 1,
    content: 'Honda Accord',
    points: 0,
    costs: 'medium',
    status: 'sport',
    type: 'sedan',
    speed: 'fast',
    refuel: 'fuel',
  },
  {
    id: 2,
    content: 'BMW 3 Series',
    points: 0,
    costs: 'expensive',
    status: 'sport',
    type: 'sedan',
    speed: 'fast',
    refuel: 'fuel',
  },
  {
    id: 3,
    content: 'Tesla Model S',
    points: 0,
    costs: 'expensive',
    status: 'premium',
    type: 'jeep',
    speed: 'fast',
    refuel: 'electrical energy',
  },
  {
    id: 4,
    content: 'BMW 7 Series',
    points: 0,
    costs: 'expensive',
    status: 'premium',
    type: 'sedan',
    speed: 'fast',
    refuel: 'electrical energy',
  },
  {
    id: 5,
    content: 'Mazda CX-5',
    points: 0,
    costs: 'medium',
    status: 'family',
    type: 'crossover',
    speed: 'medium',
    refuel: 'fuel',
  },
  {
    id: 6,
    content: 'Volkswagen Golf',
    points: 0,
    costs: 'cheap',
    status: 'compact',
    type: 'sedan',
    speed: 'slow',
    refuel: 'fuel',
  },
  {
    id: 7,
    content: 'Land Rover Defender',
    points: 0,
    costs: 'medium',
    status: 'off-road',
    type: 'jeep',
    speed: 'medium',
    refuel: 'fuel',
  },
  {
    id: 8,
    content: 'Honda CR-V',
    points: 0,
    costs: 'medium',
    status: 'family',
    type: 'crossover',
    speed: 'medium',
    refuel: 'fuel',
  },
  {
    id: 9,
    content: 'Audi A8',
    points: 0,
    costs: 'expensive',
    status: 'premium',
    type: 'sedan',
    speed: 'fast',
    refuel: 'fuel',
  },
  {
    id: 10,
    content: 'Toyota Corolla',
    points: 0,
    costs: 'medium',
    status: 'family',
    type: 'sedan',
    speed: 'medium',
    refuel: 'fuel',
  },
  {
    id: 11,
    content: 'Mercedes-AMG E63 Estate',
    points: 0,
    costs: 'expensive',
    status: 'premium',
    type: 'sedan',
    speed: 'fast',
    refuel: 'fuel',
  },
  {
    id: 12,
    content: 'Chevrolet Camaro',
    points: 0,
    costs: 'expensive',
    status: 'sport',
    type: 'sedan',
    speed: 'fast',
    refuel: 'fuel',
  },
  {
    id: 13,
    content: 'Mazda3',
    points: 0,
    costs: 'medium',
    status: 'compact',
    type: 'sedan',
    speed: 'medium',
    refuel: 'fuel',
  },
  {
    id: 14,
    content: 'Honda Civic',
    points: 0,
    costs: 'cheap',
    status: 'compact',
    type: 'sedan',
    speed: 'slow',
    refuel: 'fuel',
  },
  {
    id: 15,
    content: 'Kia Sedona',
    points: 0,
    costs: 'cheap',
    status: 'family',
    type: 'sedan',
    speed: 'slow',
    refuel: 'fuel',
  },
]
